### ISSUE TITLE
BBCode on Kunena

### ISSUE THREAD

**Issue by Flying--Dutchman** [Fedik/addfullajax-joomla#1]
*this time in the right repo.... *

Hey Fedik, 

first of all, thanks for this great plugin!

I just have one little issue; When creating or editing a post in Kunena you can't see the BBCodes. 
You can only see "Loading BB-Codes".

Is there maybe an option i did not see?

**Comment by Fedik** [comment]
No, there no option.
It sounds like initialisation problem for the BBCodes script, after it loaded by AJAX.
Something like Fedik/FullAJAX#7 may help :wink:
or http://getsite.org.ua/en/fullajax/problems-using-lightbox-and-some-other-scripts (a bit out date, but idea similar)

**Comment by Flying--Dutchman** [comment]
Wow prompt help here, thanks. :)
Will try it tomorrow and give some feedback.

**Comment by Flying--Dutchman** [comment]
That did the trick :+1: 

Now there are just some minor issues, but i can live with them.
Thank you :D

P.S.: Where can I donate?

**Comment by Flying--Dutchman** [comment]
One issue which is kinda bothering me...
sometimes the url will change in something like this:
www.domain.com/forum/#ajx/forum/news

This is not allways the case, any ideas to fix thiS?

**Comment by Fedik** [comment]
such thing can happens if you have disabled `Use HTML5 History` option, or you use old browser
