### ISSUE TITLE
Joomla 3.4 compatibility

### ISSUE THREAD

**Issue by AlexanderSk** [Fedik/addfullajax-joomla#2]
Hello,
Can you check for latest 3.4 plugin compatibility?
I am trying to debug this for some time now but  cannot seem to find a solution.

Developers console does show the ajax is fetched with code 200 but the positions are not updated..

**Comment by Fedik** [comment]
on default template seems work,

but thanks for warn, I try check more when get some time

**Comment by AlexanderSk** [comment]
Update. There seems to be an issue with mobile connection establishment. With 4G mobile connection (or LTE) in my network i fullajax doesnt load the pages as described for two sites that are both working ok in a home based internet connection.

What do you think?
a friend of mine can see the site normally via mobile internet... not the same isp thought.
What troubles me is that since the ajax request is 200 OK the script should load the positions as expected.

**Comment by Fedik** [comment]
no idea, 
but very strange,
maybe some browser thing, what browsers you tried?
