### ISSUE TITLE
Joomla 3.5 Issue

### ISSUE THREAD

**Issue by AlexanderSk** [Fedik/addfullajax-joomla#3]
Hello,

Can you confirm that fullajax is not working at all in latest 3.5 version?
I couldn't see the ajax loading at first load neither...

**Comment by AlexanderSk** [comment]
On further investigation i can see that due to php7 support Joomla team changed some things as seen here: https://github.com/joomla/joomla-cms/pull/6600
Perhaps String class rename is affecting the plugin then?

**Comment by Fedik** [comment]
thanks for open the issue, I need to check

**Comment by Allan-Turing** [comment]
Add FullAjax not worked withT3 template since the upgrade to Joomla 3.5

**Comment by Fedik** [comment]
ok, it does not work because the class renaming in Joomla 3.5

#### Quick fix

Edit `addfullajax.php` and near the line `92` replace:
`if(get_class($doc) != 'JDocumentHTML'`
to
`if(!($doc instanceof JDocumentHtml)`

I try upload new version in the weekend or next week.

**Comment by AlexanderSk** [comment]
Thank you for your time!

**Comment by AlexanderSk** [comment]
PS. we should find some time to test the module with php7 support as well. i will try to check it within next week after the plugin update...

**Comment by Allan-Turing** [comment]
Today ,we are testing the plugin with Joomla 3.5 and the T3 framework.

**Comment by Fedik** [comment]
made some test and it seems works fine with PHP 7,
new version already available for download,
